FROM debian:trixie

RUN apt-get update && apt-get upgrade -y

RUN apt-get install --no-install-recommends -y -q \
 nvi nano wget bzip2 xz-utils pkg-config make scons git

RUN apt-get install --no-install-recommends -y -q \
 qemu-user-binfmt

RUN dpkg --add-architecture arm64 && apt-get update
RUN apt-get install --no-install-recommends -y -q \
 crossbuild-essential-arm64 libsdl2-dev:arm64
